# Generated by Django 3.2 on 2021-06-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipents',
            new_name='Equipments',
        ),
    ]
