# Generated by Django 3.2 on 2021-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Describe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email_Id',
            field=models.CharField(max_length=50),
        ),
    ]
